import { NavItem, ModuleCard } from '../models/nav.model';

export const NAV_ITEMS: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    section: 'Overview',
    route: '/home',
    matIcon: 'dashboard',
    roles: ['Admin', 'Traffic Officer', 'Transport Manager', 'Compliance Officer', 'Civilian'],
  },
  {
    id: 'traffic',
    label: 'Traffic flow',
    section: 'Modules',
    route: '/traffic-flow',
    matIcon: 'traffic',
    roles: ['Admin', 'Traffic Officer'],
  },
  {
    id: 'incidents',
    label: 'Incidents',
    section: 'Modules',
    route: '/incidents',
    matIcon: 'warning_amber',
    roles: ['Admin', 'Traffic Officer'],
    badge: 3,
  },
  {
    id: 'transport',
    label: 'Transport',
    section: 'Modules',
    route: '/transport',
    matIcon: 'directions_bus',
    roles: ['Admin', 'Transport Manager'],
  },
  {
    id: 'compliance',
    label: 'Compliance',
    section: 'Modules',
    route: '/compliance',
    matIcon: 'verified_user',
    roles: ['Admin', 'Compliance Officer'],
  },
  {
    id: 'reporting',
    label: 'Reporting',
    section: 'Modules',
    route: '/reporting',
    matIcon: 'bar_chart',
    roles: ['Admin', 'Traffic Officer', 'Transport Manager', 'Compliance Officer'],
  },
  {
    id: 'notifications',
    label: 'Notifications',
    section: 'Modules',
    route: '/notifications',
    matIcon: 'notifications',
    roles: ['Admin', 'Traffic Officer', 'Transport Manager', 'Compliance Officer', 'Civilian'],
    badge: 5,
  },
  {
    id: 'map',
    label: 'Live map',
    section: 'City view',
    route: '/map',
    matIcon: 'map',
    roles: ['Admin', 'Traffic Officer', 'Civilian'],
  },
  {
    id: 'profile',
    label: 'My profile',
    section: 'Account',
    route: '/profile',
    matIcon: 'manage_accounts',
    roles: ['Admin', 'Traffic Officer', 'Transport Manager', 'Compliance Officer', 'Civilian'],
  },
];

export const MODULE_CARDS: ModuleCard[] = [
  {
    id: 'traffic',
    label: 'Traffic flow',
    description: 'Road segments, flow rates, and congestion alerts',
    matIcon: 'traffic',
    colorClass: 'text-primary',
    bgClass: 'bg-primary bg-opacity-10',
    statLabel: '12 active segments',
    statusLabel: 'Live',
    statusClass: 'success',
    route: '/traffic-flow',
    roles: ['Admin', 'Traffic Officer'],
  },
  {
    id: 'incidents',
    label: 'Incidents',
    description: 'Ongoing and resolved road incidents',
    matIcon: 'warning_amber',
    colorClass: 'text-danger',
    bgClass: 'bg-danger bg-opacity-10',
    statLabel: '3 open incidents',
    statusLabel: 'Alert',
    statusClass: 'warning',
    route: '/incidents',
    roles: ['Admin', 'Traffic Officer'],
  },
  {
    id: 'transport',
    label: 'Transport',
    description: 'Routes, stops, and live fleet tracking',
    matIcon: 'directions_bus',
    colorClass: 'text-success',
    bgClass: 'bg-success bg-opacity-10',
    statLabel: '42 vehicles active',
    statusLabel: 'Live',
    statusClass: 'success',
    route: '/transport',
    roles: ['Admin', 'Transport Manager', 'Civilian'],
  },
  {
    id: 'compliance',
    label: 'Compliance',
    description: 'Permit checks, violations, and enforcements',
    matIcon: 'verified_user',
    colorClass: 'text-warning',
    bgClass: 'bg-warning bg-opacity-10',
    statLabel: '8 checks today',
    statusLabel: 'Normal',
    statusClass: 'primary',
    route: '/compliance',
    roles: ['Admin', 'Compliance Officer'],
  },
  {
    id: 'reporting',
    label: 'Reporting',
    description: 'Analytics dashboards and scheduled reports',
    matIcon: 'bar_chart',
    colorClass: 'text-info',
    bgClass: 'bg-info bg-opacity-10',
    statLabel: 'Last run: 2h ago',
    statusLabel: 'Normal',
    statusClass: 'primary',
    route: '/reporting',
    roles: ['Admin', 'Traffic Officer', 'Transport Manager', 'Compliance Officer'],
  },
  {
    id: 'notifications',
    label: 'Notifications',
    description: 'Alerts, broadcasts, and subscriber feeds',
    matIcon: 'notifications',
    colorClass: 'text-primary',
    bgClass: 'bg-primary bg-opacity-10',
    statLabel: '5 unread',
    statusLabel: 'Pending',
    statusClass: 'warning',
    route: '/notifications',
    roles: ['Admin', 'Traffic Officer', 'Transport Manager', 'Compliance Officer', 'Civilian'],
  },
];