import { NavItem, ModuleCard } from '../models/nav.model';

// ── Role constants 
// Citizen | TrafficOfficer | TransportOperator | Admin | Compliance

export const NAV_ITEMS: NavItem[] = [
  {
    id:      'dashboard',
    label:   'Dashboard',
    section: 'Overview',
    route:   '/home',
    matIcon: 'dashboard',
    roles:   [], 
  },
  {
    id:      'traffic',
    label:   'Traffic flow',
    section: 'Modules',
    route:   '/traffic-flow',
    matIcon: 'traffic',
    roles:   ['Admin', 'TrafficOfficer'],
  },
  {
    id:      'incidents',
    label:   'Incidents',
    section: 'Modules',
    route:   '/incident',          
    matIcon: 'warning_amber',
    roles:   ['Admin', 'TrafficOfficer'],
    badge:   3,
  },
  {
    id:      'transport',
    label:   'Transport',
    section: 'Modules',
    route:   '/transport',
    matIcon: 'directions_bus',
    roles:   ['Admin', 'TransportOperator'],
  },
  {
    id:      'compliance',
    label:   'Compliance',
    section: 'Modules',
    route:   '/compliance',
    matIcon: 'verified_user',
    roles:   ['Admin', 'Compliance'],
  },
  {
    id:      'reporting',
    label:   'Reporting',
    section: 'Modules',
    route:   '/reporting',
    matIcon: 'bar_chart',
    roles:   ['Admin', 'TrafficOfficer', 'TransportOperator', 'Compliance'],
  },
  {
    id:      'notifications',
    label:   'Notifications',
    section: 'Modules',
    route:   '/notifications',
    matIcon: 'notifications',
    roles:   [], 
    badge:   5,
  },
  {
    id:      'profile',
    label:   'My profile',
    section: 'Account',
    route:   '/profile',
    matIcon: 'manage_accounts',
    roles:   [], 
  },
  {
    id:      'users',
    label:   'Users',
    section: 'Administration',
    route:   '/users',
    matIcon: 'group',
    roles:   ['Admin'],
  },
  {
    id:      'audit-logs',
    label:   'Audit logs',
    section: 'Administration',
    route:   '/audit-logs',
    matIcon: 'fact_check',
    roles:   ['Admin', 'Compliance'],
  },
];

export const MODULE_CARDS: ModuleCard[] = [
  {
    id:          'traffic',
    label:       'Traffic flow',
    description: 'Road segments, flow rates, and congestion alerts',
    matIcon:     'traffic',
    colorClass:  'text-primary',
    bgClass:     'bg-primary bg-opacity-10',
    statLabel:   '12 active segments',
    statusLabel: 'Live',
    statusClass: 'success',
    route:       '/traffic-flow',
    roles:       ['Admin', 'TrafficOfficer', 'Citizen'],
  },
  {
    id:          'incidents',
    label:       'Incidents',
    description: 'Ongoing and resolved road incidents',
    matIcon:     'warning_amber',
    colorClass:  'text-danger',
    bgClass:     'bg-danger bg-opacity-10',
    statLabel:   '3 open incidents',
    statusLabel: 'Alert',
    statusClass: 'warning',
    route:       '/incident',
    roles:       ['Admin', 'TrafficOfficer', 'Citizen'],
  },
  {
    id:          'transport',
    label:       'Transport',
    description: 'Routes, stops, and live fleet tracking',
    matIcon:     'directions_bus',
    colorClass:  'text-success',
    bgClass:     'bg-success bg-opacity-10',
    statLabel:   '42 vehicles active',
    statusLabel: 'Live',
    statusClass: 'success',
    route:       '/transport',
    roles:       ['Admin', 'TransportOperator', 'Citizen'],
  },
  {
    id:          'compliance',
    label:       'Compliance',
    description: 'Permit checks, violations, and enforcements',
    matIcon:     'verified_user',
    colorClass:  'text-warning',
    bgClass:     'bg-warning bg-opacity-10',
    statLabel:   '8 checks today',
    statusLabel: 'Normal',
    statusClass: 'primary',
    route:       '/compliance',
    roles:       ['Admin', 'Compliance'],
  },
  {
    id:          'reporting',
    label:       'Reporting',
    description: 'Analytics dashboards and scheduled reports',
    matIcon:     'bar_chart',
    colorClass:  'text-info',
    bgClass:     'bg-info bg-opacity-10',
    statLabel:   'Last run: 2h ago',
    statusLabel: 'Normal',
    statusClass: 'primary',
    route:       '/reporting',
    roles:       ['Admin', 'TrafficOfficer', 'TransportOperator', 'Compliance'],
  },
  {
    id:          'notifications',
    label:       'Notifications',
    description: 'Alerts, broadcasts, and subscriber feeds',
    matIcon:     'notifications',
    colorClass:  'text-primary',
    bgClass:     'bg-primary bg-opacity-10',
    statLabel:   '5 unread',
    statusLabel: 'Pending',
    statusClass: 'warning',
    route:       '/notifications',
    roles:       [], // all roles
  },
];